# Generated by extendr: Do not edit by hand
# nolint start

#' @usage NULL
#' @useDynLib openalexPro, .registration = TRUE
NULL

#' Return the DuckDB SQL expression that reconstructs a plain-text abstract
#' from the `abstract_inverted_index` MAP column in OpenAlex works data.
#'
#' The expression walks the map, collects (position, word) pairs, sorts by
#' position ascending, and joins words with single spaces.  Returns NULL when
#' `abstract_inverted_index` is NULL.
#'
#' @return A character scalar containing the SQL expression.
#' @export
oa_works_abstract_sql <- function() .Call(wrap__oa_works_abstract_sql)

#' Return the DuckDB SQL expression that builds a short citation string from
#' the `authorships` and `publication_year` columns in OpenAlex works data.
#'
#' Format: `"Author (year)"` / `"A & B (year)"` / `"A et al. (year)"`.
#' Null year renders as `"(n.d.)"`.  Null or empty `authorships` yields NULL.
#'
#' @return A character scalar containing the SQL expression.
#' @export
oa_works_citation_sql <- function() .Call(wrap__oa_works_citation_sql)

#' Canonicalise a DuckDB type string.
#'
#' Uppercases SQL type keywords (`BIGINT`, `VARCHAR`, `STRUCT`, …) while
#' preserving the case of struct field identifiers.  This matches DuckDB's
#' own behaviour: type keywords are case-insensitive but struct field names
#' used in `read_json(columns = …)` are matched case-sensitively.
#'
#' @param t A character scalar: a raw DuckDB type string, e.g.
#'   `"struct(author struct(display_name varchar))"`.
#' @return A character scalar with normalised type keywords.
#' @export
oa_normalize_duckdb_type <- function(t) .Call(wrap__oa_normalize_duckdb_type, t)

# nolint end
