# Generated by extendr: Do not edit by hand
# nolint start

#' @usage NULL
#' @useDynLib openalexPro, .registration = TRUE
NULL

#' Return the DuckDB SQL expression that reconstructs a plain-text abstract
#' from the `abstract_inverted_index` MAP column in OpenAlex works data.
#'
#' The expression walks the map, collects (position, word) pairs, sorts by
#' position ascending, and joins words with single spaces.  Returns NULL when
#' `abstract_inverted_index` is NULL.
#'
#' @return A character scalar containing the SQL expression.
#' @export
oa_works_abstract_sql <- function() .Call(wrap__oa_works_abstract_sql)

#' Return the DuckDB SQL expression that builds a short citation string from
#' the `authorships` and `publication_year` columns in OpenAlex works data.
#'
#' Format: `"Author (year)"` / `"A & B (year)"` / `"A et al. (year)"`.
#' Null year renders as `"(n.d.)"`.  Null or empty `authorships` yields NULL.
#'
#' @return A character scalar containing the SQL expression.
#' @export
oa_works_citation_sql <- function() .Call(wrap__oa_works_citation_sql)

#' Canonicalise a DuckDB type string.
#'
#' Uppercases SQL type keywords (`BIGINT`, `VARCHAR`, `STRUCT`, …) while
#' preserving the case of struct field identifiers.  This matches DuckDB's
#' own behaviour: type keywords are case-insensitive but struct field names
#' used in `read_json(columns = …)` are matched case-sensitively.
#'
#' @param t A character scalar: a raw DuckDB type string, e.g.
#'   `"struct(author struct(display_name varchar))"`.
#' @return A character scalar with normalised type keywords.
#' @export
oa_normalize_duckdb_type <- function(t) .Call(wrap__oa_normalize_duckdb_type, t)

#' Convert an OpenAlex snapshot to Parquet format.
#'
#' Full pipeline: schema inference (per-dataset, cached in
#' `<parquet_dir>/<dataset>/.schema_cache/unified_schema.csv`) plus parallel
#' per-file COPY via rayon.
#'
#' @param snapshot_dir Path to the snapshot root (contains a `data/` subdir).
#' @param parquet_dir  Output directory for Parquet files.
#' @param data_sets    Character vector of dataset names, or `character(0)` for
#'   all datasets found under `snapshot_dir/data/` (excluding `merged_ids`).
#' @param workers      Number of parallel workers (`1` = sequential).
#' @param sample_size  Files to sample for schema inference (`0` = all).
#' @param memory_limit DuckDB memory limit, e.g. `"8GB"` (`""` = no limit).
#' @param temp_dir     DuckDB temp directory (`""` = system default).
#' @param verbose      Print progress to stderr.
#' @return Invisibly returns `NULL`.
#' @export
oa_snapshot_to_parquet <- function(snapshot_dir, parquet_dir, data_sets, workers, sample_size, memory_limit, temp_dir, verbose) .Call(wrap__oa_snapshot_to_parquet, snapshot_dir, parquet_dir, data_sets, workers, sample_size, memory_limit, temp_dir, verbose)

#' Parallel per-file conversion for OpenAlex API JSON responses.
#'
#' Schema inference (including type normalisation) is performed in R and the
#' result is passed as pre-computed SQL fragments.  This function handles only
#' the parallel execution of COPY statements via rayon.
#'
#' @param input_files  Character vector of input JSON file paths.
#' @param output_files Character vector of output Parquet file paths
#'   (same length as `input_files`).
#' @param array_field  Name of the JSON array key (`"results"`, `"group_by"`),
#'   or `""` for single-record files.
#' @param list_type    DuckDB STRUCT type string for array items, e.g.
#'   `"STRUCT(id VARCHAR, title VARCHAR)[]"`.  `""` = use `read_json_auto`.
#' @param extra_select SQL fragment appended after `SELECT *`, e.g.
#'   `", abstract_expr AS abstract, 'p1' AS page"`.
#' @param workers      Number of parallel workers.
#' @param verbose      Print failures to stderr.
#' @return Invisibly returns `NULL`.
#' @export
oa_api_files_to_parquet <- function(input_files, output_files, array_field, list_type, extra_select, workers, verbose) .Call(wrap__oa_api_files_to_parquet, input_files, output_files, array_field, list_type, extra_select, workers, verbose)

#' Build a two-stage ID-lookup index for a single Parquet corpus directory.
#'
#' Stage 1: per-file shard indexes (parallel via rayon).
#' Stage 2: combine shards into `<corpus_name>_id_idx.parquet`.
#'
#' Returns the path to the created index file as a character scalar.
#'
#' @param corpus_dir   Path to a single dataset Parquet directory.
#' @param workers      Number of parallel workers for Stage 1.
#' @param memory_limit DuckDB memory limit (`""` = no limit).
#' @param overwrite    If `TRUE`, rebuild an existing index.
#' @param verbose      Print progress to stderr.
#' @return Character scalar: path to the index file.
#' @export
oa_build_corpus_index <- function(corpus_dir, workers, memory_limit, overwrite, verbose) .Call(wrap__oa_build_corpus_index, corpus_dir, workers, memory_limit, overwrite, verbose)

#' Look up records by OpenAlex ID using a pre-built index.
#'
#' Reads the index file, filters to the requested IDs, and extracts matching
#' rows into the `output` directory (which must not already exist).
#'
#' @param index_file Path to the index Parquet file (created by
#'   [oa_build_corpus_index()]).
#' @param ids        Character vector of OpenAlex IDs (long or short form).
#' @param output     Output directory path.  Must not already exist.
#' @param workers    Number of parallel workers for file extraction.
#' @param verbose    Print progress to stderr.
#' @return Invisibly returns `NULL`.
#' @export
oa_lookup_by_id <- function(index_file, ids, output, workers, verbose) .Call(wrap__oa_lookup_by_id, index_file, ids, output, workers, verbose)

# nolint end
